# Generated by Django 4.2.11 on 2024-08-04 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcertificados',
            name='inmueble',
        ),
        migrations.RemoveField(
            model_name='solicitudcertificados',
            name='tipo_certificado',
        ),
        migrations.RemoveField(
            model_name='solicituddestacados',
            name='inmueble',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='Destacados',
        ),
        migrations.DeleteModel(
            name='SolicitudCertificados',
        ),
        migrations.DeleteModel(
            name='SolicitudDestacados',
        ),
        migrations.DeleteModel(
            name='TipoCertificado',
        ),
    ]
