# Generated by Django 4.2.11 on 2024-08-04 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_solicitudcertificados_inmueble_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCertificado',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('badge', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudDestacados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('A', 'Aceptar'), ('R', 'Rechazar')], max_length=1)),
                ('inmueble', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.inmueble')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudCertificados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('A', 'Aceptar'), ('R', 'Rechazar')], max_length=1)),
                ('inmueble', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.inmueble')),
                ('tipo_certificado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tipocertificado')),
            ],
        ),
        migrations.CreateModel(
            name='Destacados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_destacado', models.DateTimeField(auto_now_add=True, null=True)),
                ('inmueble', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.inmueble')),
            ],
        ),
        migrations.AddField(
            model_name='certificado',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tipocertificado'),
        ),
    ]
