# Generated by Django 5.0.2 on 2024-02-12 20:35

import django.db.models.deletion
import essentials
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArriendoVenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='images/', validators=[essentials.validate_file_size])),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoInmueble',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=80)),
                ('descripcion', models.CharField(max_length=300)),
                ('area', models.CharField(max_length=7)),
                ('area_construida', models.CharField(max_length=7)),
                ('habitaciones', models.CharField(max_length=3)),
                ('banios', models.CharField(max_length=3)),
                ('arriendo_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.arriendoventa')),
                ('certificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.certificado')),
                ('duenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InmuebleImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.imagenes')),
                ('id_inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.inmueble')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=10)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.departamento')),
            ],
        ),
        migrations.AddField(
            model_name='inmueble',
            name='municipio_ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.municipio'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pais'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='tipo_inmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tipoinmueble'),
        ),
    ]
