# Generated by Django 4.2.11 on 2024-04-11 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_arriendoventa_id_alter_tipodocumento_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arriendoventa',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='certificado',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='departamento',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='inmueble',
            old_name='descripcion',
            new_name='descriptionripcion',
        ),
        migrations.RenameField(
            model_name='municipio',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='pais',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='tipodocumento',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='tipoinmueble',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='tipousuario',
            old_name='desc',
            new_name='description',
        ),
    ]
