# Generated by Django 4.2.11 on 2024-04-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_usuario_celular_usuario_permitir_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodocumento',
            name='description',
            field=models.CharField(max_length=40),
        ),
    ]
