# Generated by Django 4.2.11 on 2024-04-11 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_tipodocumento_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_nacimiento',
        ),
    ]
