# Generated by Django 4.2.11 on 2024-04-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCobro',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=40)),
            ],
        ),
    ]
