# Generated by Django 4.2.11 on 2024-04-14 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_tipocobro'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='tipo_cobro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.tipocobro'),
        ),
    ]
