# Generated by Django 4.2.11 on 2024-04-15 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_inmueble_tipo_cobro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmueble',
            old_name='descriptionripcion',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='certificado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.certificado'),
        ),
    ]
