# Generated by Django 4.2.11 on 2024-04-15 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_descriptionripcion_inmueble_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenes',
            name='inmueble',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.inmueble'),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='img',
            field=models.ImageField(upload_to='inmuebles_img'),
        ),
        migrations.DeleteModel(
            name='InmuebleImg',
        ),
    ]
