# Generated by Django 4.2.11 on 2024-04-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_imagenes_inmueble_alter_imagenes_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
