# Generated by Django 4.2.11 on 2024-04-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_departamento_id_alter_municipio_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
