# Generated by Django 4.2.11 on 2024-04-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_municipio_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
