# Generated by Django 4.2.11 on 2024-04-16 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_departamento_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='municipio_ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.municipio'),
        ),
    ]
