# Generated by Django 4.2.11 on 2024-04-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_inmueble_municipio_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='img',
            field=models.ImageField(null=True, upload_to='inmuebles'),
        ),
    ]
