# Generated by Django 4.2.11 on 2024-04-19 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_imagenes_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='inmueble',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='main.inmueble'),
        ),
    ]
