# Generated by Django 4.2.11 on 2024-04-25 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_inmueble_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='description',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='certificado',
        ),
        migrations.AddField(
            model_name='certificado',
            name='fecha_certificacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='inmueble',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.inmueble'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
