# Generated by Django 4.2.11 on 2024-04-25 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_inmueble_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='InmueblesDestacados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_destacado', models.DateTimeField(auto_now_add=True, null=True)),
                ('inmueble', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.inmueble')),
            ],
        ),
    ]
