# Generated by Django 4.2.11 on 2024-04-25 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_inmueblesdestacados'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InmueblesDestacados',
            new_name='Destacados',
        ),
    ]
