# Generated by Django 4.2.11 on 2024-04-26 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_rename_inmueblesdestacados_destacados'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCertificado',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='certificado',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tipocertificado'),
        ),
    ]
