# Generated by Django 4.2.11 on 2024-04-28 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_tipocertificado_certificado_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudDestacados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('A', 'Aceptado'), ('R', 'Rechazado')], max_length=1)),
                ('inmueble', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.inmueble')),
            ],
        ),
    ]
