# Generated by Django 4.2.11 on 2024-04-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_solicitudcertificados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
