# Generated by Django 4.2.11 on 2024-04-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_inmueble_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='precio',
            field=models.BigIntegerField(),
        ),
    ]
